version: '3'

volumes:
  crypto_price_trigger_local_postgres_data: {}
  crypto_price_trigger_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: crypto_price_trigger_local_django
    container_name: crypto_price_trigger_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: crypto_price_trigger_production_postgres
    container_name: crypto_price_trigger_local_postgres
    volumes:
      - crypto_price_trigger_local_postgres_data:/var/lib/postgresql/data
      - crypto_price_trigger_local_postgres_data_backups:/backups
    env_file:
      - .env
  redis:
    image: redis:6
    container_name: crypto_price_trigger_local_redis

  celeryworker:
    <<: *django
    image: crypto_price_trigger_local_celeryworker
    container_name: crypto_price_trigger_local_celeryworker
    ports: []
    command: /start-celeryworker