# Generated by Django 4.1.8 on 2023-05-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0003_alter_users_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=100)),
                ("stock_name", models.CharField(max_length=100)),
                ("stock_price", models.IntegerField()),
                ("alert_sent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Deleted", "Deleted"),
                            ("Triggered", "Triggered"),
                        ],
                        default="Created",
                        max_length=15,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
            options={
                "db_table": "alert",
            },
        ),
    ]
